### ISSUE TITLE
Messages v6.5

### ISSUE THREAD

**Issue by AlekseyMamaev** [vladislav805/APIdog#100]
Довольно таки **часто** возникает проблема, что **в диалоге появляется некий отступ от скролла**. Наблюдается не во всех диалогах. 

![apidog](https://cloud.githubusercontent.com/assets/21069172/20860128/e35ad078-b981-11e6-9e21-40c3b0c9ef07.png)

> `table {
    border-spacing: 0;
}`

![apidog1](https://cloud.githubusercontent.com/assets/21069172/20860129/e35bc082-b981-11e6-8b9b-238c265bf3f1.png)

> `table {
    border-spacing: 0;
    width: 100%;
}`

**Comment by vladislav805** [comment]
В курсе. Однако, не помню почему, так делать не стоит. Кажется, из-за этого растягивался блок за границы видимого, если есть широкие изображения внутри него
