### ISSUE TITLE
Forwarded message doesn't showing

### ISSUE THREAD

**Issue by Templariumer** [vladislav805/APIdog#102]
![image](https://cloud.githubusercontent.com/assets/19695315/20937798/14bec78c-bc1b-11e6-8305-5ce0cbdc2022.png)
There's a video and some links besides text.
Not a programmer to give any hint about that.

**Comment by vladislav805** [comment]
Are you sure, that message is loaded?

**Comment by Templariumer** [comment]
How can I check that?
It loads on VK and VK mobile for iOS, but here it's just blank
Also, it loads normally on 6.4

**Comment by vladislav805** [comment]
Oh, yes. Don't output forwarded messages.
