### ISSUE TITLE
Failed to start a dialog

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#17]
When click "Write message" from list of friend or user's page. 
![default](https://cloud.githubusercontent.com/assets/17404606/17649004/f74d10b2-6230-11e6-96a3-de452989acf7.PNG)

> TypeError: result.items is undefined
> IM.show/load/<()
> minify.php:7866
> APIRequest.prototype._onCompleteLoad()
> minify.php:18876
> ExtensionRequest.prototype._onResponse()
> minify.php:19064
> <анонімно>
> minify.php:19085
> handleExtensionEvent()
> minify.php:4048
> <анонімно>
> minify.php:4080
> minify.php:7866:6

**Comment by who0ps** [comment]
From friend list not fixed.

**Comment by vladislav805** [comment]
Да подожди ты со списком друзей то. Profile.js дай до конца переписать
