### ISSUE TITLE
Error and bug, when creating a friend list

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#18]
When crating:

> TypeError: response.items[i].lists is undefined
> Friends.showFriends()
> minify.php:5235
> Friends.explain/<()
> minify.php:5184
> APIRequest.prototype._onCompleteLoad()
> minify.php:18876
> ExtensionRequest.prototype._onResponse()
> minify.php:19064
> <анонімно>
> minify.php:19085
> handleExtensionEvent()
> minify.php:4048
> <анонімно>
> minify.php:4080
> minify.php:5235:9

But list will be created.
Also ignoring "0" at start of name. 
001 -> 1
001001 -> 1001

**Comment by who0ps** [comment]
Also error, when trying to open list.

> TypeError: response.items[i].lists is undefined
> Friends.showFriends()
> minify.php:5235
> Friends.explain()
> minify.php:5173
> Site.Go()
> minify.php:23898
> <анонімно>
> minify.php:17436
> minify.php:5235:9

**Comment by vladislav805** [comment]
"0" is trimmed by VK API.
Exceptions fixed in `v6.4.5-i`.
