### ISSUE TITLE
Broken about link in readme.md

### ISSUE THREAD

**Issue by ex47** [vladislav805/APIdog#2]
APIdog/README.md

![screenshot_13](https://cloud.githubusercontent.com/assets/2480069/17522628/6a4bfda0-5e60-11e6-8bdd-e52a2bd254c9.png)

Leads to https://apidog.ru/v6.5/about.php whis is 404
The correct link is https://apidog.ru/6.5/about.php

Also, "о проекте".

**Comment by vladislav805** [comment]
Fixed. Thanks!
