### ISSUE TITLE
Editing and deleting notes has no visual effects

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#25]
But works.

**Comment by who0ps** [comment]
Editing not fixed

**Comment by vladislav805** [comment]
Why for me all works?

**Comment by who0ps** [comment]
It works, but on first query after entering captcha editing has no visual effect and change name to this (screen):
![default](https://cloud.githubusercontent.com/assets/17404606/18043645/dde3194e-6dd1-11e6-9518-273f427db1fd.PNG)
