### ISSUE TITLE
Online app detection not works 

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#35]
Until click "Refresh"
![default](https://cloud.githubusercontent.com/assets/17404606/17651697/2d632f80-6275-11e6-9108-50feab3bff7d.png)

**Comment by vladislav805** [comment]
- only in /friends page *

**Comment by vladislav805** [comment]
friends.get returns incorrect values for "online", "online_mobile" and "online_app" (it can be -1)
