### ISSUE TITLE
People Search bugs

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#41]
- [x] Year of birth. Can't be more, than 2002 (every year+1).
- [x] Age. When choose "from" 19, field "to" can't be less. And backwards.
- [x] Checkboxes "with photo" and "online" has no effect.
- [x] Birthday can be set as 31/02. February. Again.

**Comment by who0ps** [comment]
Not fixed.

Checkboxes missed.

**Comment by vladislav805** [comment]
How you can set 30 day in febrary, if on change month, days recomplute?

**Comment by who0ps** [comment]
Not recompute.

**Comment by vladislav805** [comment]
>  Checkboxes "with photo" and "online" has no effect.

Bug VK API.
