### ISSUE TITLE
Do not open video

### ISSUE THREAD

**Issue by vladislav805** [vladislav805/APIdog#54]
> TypeError: Audios.getPlayer(...) is null
> Audios.isPlaying()
> assembler.php:2124
> Video.getVideo/<()
> assembler.php:28782
> APIRequest.prototype._onCompleteLoad()
> assembler.php:19475
> DirectRequest.prototype.mListener()
> assembler.php:19560
> <anonymous>

**Comment by who0ps** [comment]
Not fixed
