### ISSUE TITLE
No audios?

### ISSUE THREAD

**Issue by ex47** [vladislav805/APIdog#6]
Audios don't play and their markup is broken in posts.

![screenshot_14](https://cloud.githubusercontent.com/assets/2480069/17643150/925f313e-6169-11e6-908c-f8d7fc018df6.png)

**Comment by vladislav805** [comment]
v6.4?

**Comment by ex47** [comment]
6.5

**Comment by vladislav805** [comment]
So strange... why is the audio item so looks. In 6.5, I rewrite the layout, and it is far from this.
What is not played is fine, there is not implemented the player.

**Comment by ex47** [comment]
I think it is my language setting, but I can't change it -_-
![screenshot_15](https://cloud.githubusercontent.com/assets/2480069/17645887/bd338332-61ba-11e6-8802-a3b8c65f4364.png)

**Comment by vladislav805** [comment]
Refreshing page solve this problem ;)

**Comment by ex47** [comment]
Okay, I've managed to change language and settings became normal
![screenshot_16](https://cloud.githubusercontent.com/assets/2480069/17645911/bb207d42-61bb-11e6-9e2f-e09d57de46ad.png)

Still no audio though.
.

**Comment by vladislav805** [comment]
Something I missed the point about audio and languages. Are we talking about?

**Comment by ex47** [comment]
Кхм. Я подумал что из-за настроек языка не работает аудио. Просто пропустил строку 

> What is not played is fine, there is not implemented the player.

А теперь ясно, что пока никаких аудиозаписей :D Но верстка всё равно поехавшая.

**Comment by vladislav805** [comment]
О, русский язык!

**Comment by ex47** [comment]
Да, можно и так :D
