### ISSUE TITLE
Does not opens dialog with somebody

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#63]
> ReferenceError: result is not defined
> Site.Get()
> assembler.php:26507
> IM.Resolve()
> assembler.php:10584
> Site.Go()
> assembler.php:25530
> <анонімно>
> assembler.php:18238
> assembler.php:26507:53

**Comment by vladislav805** [comment]
Example? I can't reproduce the problem

**Comment by who0ps** [comment]
11 days ago was actual.
