### ISSUE TITLE
Deployment Guide

### ISSUE THREAD

**Issue by ex47** [vladislav805/APIdog#7]
"Readme.md" says the project uses PHP and NodeJS , alse some kind of DB is mentioned. 

Could you please provide some manual to install APIdog locally for dev purposes?

**Comment by vladislav805** [comment]
At the moment is not provided. Will be a little later.

**Comment by ex47** [comment]
Чем быстрее, тем лучше. Люди смогли бы помочь в разработке.

**Comment by vladislav805** [comment]
Или спереть код. Но с другой стороны, тогда зачем нужен опенсорс? :D

**Comment by ex47** [comment]
Эмм. Код и так лежит.

**Comment by vladislav805** [comment]
Верно. Но запустить сможет, как мне кажется, не каждый. Как минимум, отсутствует файл zero.config.php и БД.

**Comment by ex47** [comment]
Каждый кто захочет. Я бы мог посидеть, разобраться что куда и в конце-концов всё настроить... Но в этом нет смысла ибо я не собираюсь хостить еще один апидог. 

Получается что для того, кто хочет использовать в корыстных целях препятствия минимальны, а для того, кто хочет создать пару PR - неприветливая атмосфера.

**Comment by vladislav805** [comment]
Хм, однако. Создам как-нибудь файлик установки..
