### ISSUE TITLE
Changing name has no visual effect

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#76]
After click "Save" console:

![default](https://cloud.githubusercontent.com/assets/17404606/18946125/2dfab0b4-8636-11e6-9457-025b44c74327.png)

Need to add notification.
V6.4

**Comment by who0ps** [comment]
Have visual effect "Saved" notification, but I want to see "Declined".

**Comment by vladislav805** [comment]
I understand. I think, that I just now it fixed.

**Comment by vladislav805** [comment]
Oh, shit. I forgot rebuild minified file. Please, check it now.

**Comment by who0ps** [comment]
It works, but time of showing notification is too short to read it.

**Comment by vladislav805** [comment]
15 seconds should be enough
