### ISSUE TITLE
Enable background images caching for custom themes

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#79]
At now - disabled.

**Comment by vladislav805** [comment]
One question: how you it imagine? If image hosted by other server, how we can notify browser for saving image to cache? -- In no way.

**Comment by who0ps** [comment]
We can host that images.
How many themes uses background (with private)?

**Comment by vladislav805** [comment]
I will not every theme test. And the script, which will parse CSS and copy the backgrounds/sprites to us to write is not particularly appropriate. For extra load on the server and that the users then will not be able to change the backgrounds.
