### ISSUE TITLE
Divide into modules all front-end code

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#80]
And download only if needded.

**Comment by vladislav805** [comment]
Create static minimal loader-controller, which will be load in every visit to site, and that can cache all modules. Modules (for example, Templates, Wiki, MediaPlayer, etc) will be load only if required by user.

**Comment by vladislav805** [comment]
- ~~Base (small static block: loading libs, modules)~~
- ~~libs (external frameworks)~~
  - ~~SugarJS (syntax sugar)~~
  - ~~Chart.js (graphs)~~
  - Video.js (video-player)
- ~~Templates (html-templates for blocks)~~
- Wiki (parsing and displaying wiki-pages)
- Media (base for showing media-files)
- Attachment (base for showing attachments)
- Utils (helpers)
- ~~Profiles~~
- ~~Groups~~
- ~~Apps~~
- ~~Friends~~
- ~~Feed~~
  - ~~Notifications~~
- ~~Photos~~
- ~~Video~~
- ~~Audio~~
- ~~Documents~~
- ~~Fave~~
- Communications
  - PrivateMessage
    - Mail
    - IM
  - Comments
  - UI
    - Smiles
    - Stickers
- ~~Settings~~
- Extension
