### ISSUE TITLE
Cyrillic symbols issue

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#83]
After captcha entered.

```
TypeError: Site.APIRequestCallbacks[a.requestId] is not a function
<анонімно>
default.min.js:178
handleExtensionEvent()
default.min.js:176
<анонімно>
default.min.js:178
[Докладніше]default.min.js:178:281
```

[More](https://apidog.ru/6.4/#support/30940)

**Comment by vladislav805** [comment]
Text -> messages.send -> success : OK
Text -> messages.send -> captcha : request_params contains text in windows-1251. (in direct and extension cases, equals result)

**Comment by vladislav805** [comment]
https://vk.com/support?act=show&id=23430294

**Comment by vladislav805** [comment]
Sent for support ping.

**Comment by vladislav805** [comment]
They said, that "developers doesn't notice them about time of fixing"

**Comment by vladislav805** [comment]
After 1.5 years vk does not respond.
