### ISSUE TITLE
Find and fix errors from php_errors.log

### ISSUE THREAD

**Issue by who0ps** [vladislav805/APIdog#93]

**Comment by vladislav805** [comment]
Listed all from 21 October. I think, that all fixed..

**Comment by who0ps** [comment]
Look at 23-Oct-2016 11:17:21 and 23-Oct-2016 11:21:27

**Comment by vladislav805** [comment]
See it.

**Comment by vladislav805** [comment]
Fixed. Waiting for yet anothers.
Also: fixed getting bitrate of audio. But... it so longtime operation.
